name: build

on:
  push:
    branches:
    tags:
    paths:
      - "./**"
  pull_request:
    paths:
      - "./**"

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker Hub
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo ${DOCKER_HUB_TOKEN} | docker login -u shibanet0 --password-stdin

      - name: deploy tagged (latest) to dockerhub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          ref=$(git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD) && version="${ref}"-$(git log -1 --format=%h)-$(date +%Y%m%dT%H:%M:%S) && echo "version=$version" && \
          docker buildx build --push \
              --build-arg version=${version} \
              --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg GIT_BRANCH=${ref} --build-arg GITHUB_REF=${GITHUB_REF} \
              --platform linux/amd64,linux/arm64 \
              -t shibanet0/docker-browser:${ref} -t shibanet0/docker-browser:latest \
              -f docker/Dockerfile \
              .
